/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./../src/components/icon.vue')['default']
    LayoutAbout: typeof import('./../src/components/layout/about.vue')['default']
    LayoutFooter: typeof import('./../src/components/layout/footer.vue')['default']
    LayoutHeader: typeof import('./../src/components/layout/header.vue')['default']
    LayoutMain: typeof import('./../src/components/layout/main.vue')['default']
    LayoutPrint: typeof import('./../src/components/layout/print.vue')['default']
    LayoutShare: typeof import('./../src/components/layout/share.vue')['default']
    Modal: typeof import('./../src/components/modal.vue')['default']
    PageAside: typeof import('./../src/components/page/aside.vue')['default']
    PageContent: typeof import('./../src/components/page/content.vue')['default']
    PagePassword: typeof import('./../src/components/page/password.vue')['default']
    TBackTop: typeof import('tdesign-vue-next/esm')['BackTop']
    TButton: typeof import('tdesign-vue-next/esm')['Button']
    TConfigProvider: typeof import('tdesign-vue-next/esm')['ConfigProvider']
    TDescriptions: typeof import('tdesign-vue-next/esm')['Descriptions']
    TDescriptionsItem: typeof import('tdesign-vue-next/esm')['DescriptionsItem']
    TDropdown: typeof import('tdesign-vue-next/esm')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next/esm')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next/esm')['DropdownMenu']
    TEmpty: typeof import('tdesign-vue-next/esm')['Empty']
    TForm: typeof import('tdesign-vue-next/esm')['Form']
    TFormItem: typeof import('tdesign-vue-next/esm')['FormItem']
    TImageViewer: typeof import('tdesign-vue-next/esm')['ImageViewer']
    TInput: typeof import('tdesign-vue-next/esm')['Input']
    TLoading: typeof import('tdesign-vue-next/esm')['Loading']
    Tooltip: typeof import('./../src/components/tooltip.vue')['default']
    TRadioButton: typeof import('tdesign-vue-next/esm')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next/esm')['RadioGroup']
    TSlider: typeof import('tdesign-vue-next/esm')['Slider']
    TTabPanel: typeof import('tdesign-vue-next/esm')['TabPanel']
    TTabs: typeof import('tdesign-vue-next/esm')['Tabs']
    TTextarea: typeof import('tdesign-vue-next/esm')['Textarea']
    TTooltip: typeof import('tdesign-vue-next/esm')['Tooltip']
    TTree: typeof import('tdesign-vue-next/esm')['Tree']
  }
}
